// Rodada 18 (tutorial18) — glossário da indústria (pesquisável na ajuda e no Ctrl+K). Sem DOM: testável.

import { l, type L } from '../data/world';

export interface Gloss18 { id: string; term: L; def: L; ex?: L; alt?: string[] }
type P = [string, string];
const G: Gloss18[] = [];
const g = (id: string, term: P, def: P, ex?: P, alt: string[] = []): void => { G.push({ id, term: l(...term), def: l(...def), ex: ex ? l(...ex) : undefined, alt }); };

g('deal360', ['Contrato 360', '360 deal'], ['O selo ganha parte de TUDO do artista (shows, merch, sync, publicidade), não só das gravações; em troca investe mais.', 'The label takes a share of EVERYTHING the act earns (shows, merch, sync, endorsements), not just recordings; in return it invests more.'], ['15% dos shows e 25% do merch para o selo (comum após 2005).', '15% of shows and 25% of merch to the label (common after 2005).'], ['360']);
g('masters', ['Masters (fonograma)', 'Masters (sound recording)'], ['A gravação original. Quem tem o master controla cópias, licenças e streams da gravação.', 'The original recording. Whoever owns the master controls copies, licences and streams of the recording.'], ['Artista que regrava o disco cria um master novo que ele controla.', 'An act re-recording an album creates a new master they control.'], ['master', 'fonograma']);
g('recoup', ['Recuperação (recoupment)', 'Recoupment'], ['O adiantamento e certos custos são descontados dos royalties do artista antes que ele receba algo.', 'The advance and certain costs are deducted from the act\'s royalties before they get paid anything.'], ['Adiantamento de $100k com royalty de $1/disco: o artista só recebe após 100 mil cópias.', 'A $100k advance at $1/record royalty: the act is paid only after 100k copies.'], ['recoupment', 'recuperar']);
g('crosscoll', ['Colateralização cruzada', 'Cross-collateralization'], ['Prejuízo de um disco (ou contrato) é descontado dos royalties de outro.', 'One record\'s (or deal\'s) unrecouped balance is deducted from another\'s royalties.'], ['Disco 1 deve $50k; o sucesso do disco 2 paga essa dívida antes do artista.', 'Album 1 owes $50k; album 2\'s success pays that first, before the act.'], ['cross-collateralization', 'cross']);
g('advance', ['Adiantamento', 'Advance'], ['Dinheiro pago ao artista na assinatura, recuperável pelos royalties (não é presente).', 'Money paid to the act on signing, recoupable from royalties (not a gift).'], ['Adiantamento alto = mais chance de aceitar e mais tempo até lucrar.', 'A big advance = better acceptance chance and longer until profit.']);
g('royalty', ['Royalty', 'Royalty'], ['Porcentagem da receita paga ao artista ou autor por unidade/stream.', 'Percentage of revenue paid to the act or writer per unit/stream.'], ['15% do preço de atacado é típico de contrato de artista.', '15% of wholesale is typical in an artist deal.']);
g('option', ['Opção', 'Option'], ['Direito do selo (não obrigação) de estender o contrato por mais discos.', 'The label\'s right (not obligation) to extend the deal for more records.'], ['Contrato de 1 disco + 4 opções: o selo decide a cada disco.', 'A 1-album deal + 4 options: the label decides after each record.']);
g('mechanical', ['Direito mecânico', 'Mechanical royalty'], ['Pago ao autor/editora por cada cópia (física, download ou stream) de uma composição.', 'Paid to the writer/publisher for every copy (physical, download or stream) of a composition.'], ['Taxa legal nos EUA: 2¢ por faixa (1909–1977), 9,1¢ em 2006.', 'US statutory rate: 2¢ per track (1909–1977), 9.1¢ in 2006.'], ['mecânico']);
g('performance', ['Direito de execução', 'Performance royalty'], ['Pago ao autor/editora quando a obra toca em público: rádio, TV, shows, bares, streaming.', 'Paid to the writer/publisher when the work is played publicly: radio, TV, shows, bars, streaming.'], ['Tema de novela gera execução a cada reprise.', 'A soap theme earns performance on every rerun.'], ['execução', 'execucao']);
g('neighbouring', ['Direitos conexos', 'Neighbouring rights'], ['Pagos aos donos do master e aos intérpretes quando a GRAVAÇÃO é executada (fora dos EUA, rádio aberta).', 'Paid to master owners and performers when the RECORDING is played publicly (outside the US for terrestrial radio).'], ['Rádio no Reino Unido paga conexos; nos EUA, não (só rádio digital).', 'UK radio pays neighbouring rights; US terrestrial radio does not.'], ['conexos', 'neighboring']);
g('pro', ['Sociedade de arrecadação (PRO)', 'Performing rights organisation (PRO)'], ['Entidade que licencia e arrecada direitos de execução para autores: ASCAP, BMI, PRS, GEMA, SACEM, JASRAC.', 'Body that licenses and collects performance rights for writers: ASCAP, BMI, PRS, GEMA, SACEM, JASRAC.'], ['Cada uma cobra taxa e paga com atraso de meses.', 'Each charges a fee and pays months late.'], ['ascap', 'bmi', 'prs', 'sociedade']);
g('ecad', ['ECAD', 'ECAD'], ['Escritório central que arrecada execução pública no Brasil (desde 1973) e repassa às associações (UBC, Abramus...).', 'Brazil\'s central office collecting public performance (since 1973), passing it to societies (UBC, Abramus...).'], ['Show em Recife sem borderô = autor não recebe.', 'A show in Recife without a set list filed = the writer is not paid.']);
g('blackbox', ['Caixa preta', 'Black box'], ['Dinheiro arrecadado que não achou dono (metadados ruins). Após o prazo, é dividido entre os grandes.', 'Collected money that found no owner (bad metadata). After the deadline it is split among the big players.'], ['Split cadastrado errado → royalties presos 3 anos e perdidos.', 'A badly registered split → royalties stuck 3 years and lost.'], ['black box']);
g('split', ['Split (divisão)', 'Split'], ['Quanto de uma obra pertence a cada autor/editora; deve somar 100%.', 'How much of a work belongs to each writer/publisher; must total 100%.'], ['Feat com 3 autores: 40/30/30.', 'A feat with 3 writers: 40/30/30.']);
g('sample', ['Sample / autorização', 'Sample clearance'], ['Usar trecho de outra gravação exige licença do master E da obra.', 'Using a piece of another recording needs a licence for the master AND the composition.'], ['Sample sem autorização = processo e retirada do disco.', 'An uncleared sample = lawsuit and the record pulled.'], ['clearance']);
g('compulsory', ['Licença compulsória', 'Compulsory licence'], ['Nos EUA qualquer um pode gravar cover de obra já lançada pagando o mecânico legal; fora, precisa de autorização.', 'In the US anyone may cover a released work by paying the statutory mechanical; elsewhere it needs permission.']);
g('termination', ['Rescisão de 35 anos', '35-year termination'], ['Lei dos EUA (obras de 1978+): o autor pode recuperar direitos cedidos após 35 anos.', 'US law (works from 1978+): the author may reclaim granted rights after 35 years.'], ['Em 2013 os primeiros autores pediram de volta seus masters/obras.', 'In 2013 the first authors reclaimed their masters/works.']);
g('sync', ['Sync (sincronização)', 'Sync licensing'], ['Licença para usar música junto com imagem: filme, série, anúncio, game. Paga taxa ao master e à obra.', 'Licence to use music with picture: film, series, ad, game. Pays a fee to the master and the composition.'], ['Música em anúncio de carro: $50k + volta às paradas.', 'A song in a car ad: $50k + back in the charts.'], ['sincronização']);
g('publishing', ['Edição musical (publishing)', 'Music publishing'], ['Negócio das COMPOSIÇÕES (não gravações): licenciar, arrecadar e promover obras.', 'The business of COMPOSITIONS (not recordings): licensing, collecting and promoting works.'], ['Editora fica com ~50% da parte autoral clássica.', 'A publisher keeps ~50% of the classic writer share.'], ['editora']);
g('pd', ['P&D (prensagem e distribuição)', 'P&D (pressing & distribution)'], ['Acordo em que uma major prensa e distribui o disco do indie; o indie paga e às vezes recebe adiantamento.', 'Deal where a major presses and distributes an indie\'s record; the indie pays and sometimes gets an advance.'], ['P&D com mínimo de 4 lançamentos/ano.', 'P&D with a minimum of 4 releases a year.']);
g('distribution', ['Distribuição', 'Distribution'], ['Levar o disco às lojas (físico) ou plataformas (digital), cobrando uma taxa sobre a venda.', 'Getting the record to shops (physical) or platforms (digital), for a fee on sales.'], ['Taxa de 20–30% no físico; 10–15% no digital.', '20–30% fee on physical; 10–15% on digital.']);
g('aggregator', ['Agregador', 'Aggregator'], ['Distribuidora digital (TuneCore, CD Baby, DistroKid) que entrega músicas às plataformas por % ou assinatura.', 'Digital distributor (TuneCore, CD Baby, DistroKid) delivering music to platforms for a % or subscription.'], ['Assinatura barata, mas sem pitching editorial.', 'Cheap subscription, but no editorial pitching.'], ['distrokid', 'tunecore']);
g('pitch', ['Pitching de playlist', 'Playlist pitching'], ['Enviar a faixa para curadores de playlists editoriais antes do lançamento.', 'Sending the track to editorial playlist curators before release.'], ['Pitch 4 semanas antes; aceitação depende de dados e relação.', 'Pitch 4 weeks before; acceptance depends on data and relations.'], ['pitching']);
g('playlist', ['Playlist', 'Playlist'], ['Lista curada (editorial, algorítmica ou de usuário) que gera descoberta em massa; dependência cria quedas.', 'Curated list (editorial, algorithmic or user) driving mass discovery; dependence creates crashes.']);
g('prorata', ['Pró-rata', 'Pro-rata'], ['Modelo do streaming: toda a receita do território vai a um bolo dividido pela fatia de streams.', 'Streaming model: all territory revenue goes into one pot split by share of streams.'], ['Seu fã que ouve só você paga, na prática, os artistas mais tocados.', 'Your fan who only plays you effectively pays the most-streamed acts.']);
g('usercentric', ['User-centric', 'User-centric'], ['Alternativa ao pró-rata: a assinatura de cada usuário vai só para quem ele ouviu.', 'Alternative to pro-rata: each user\'s subscription goes only to what they played.']);
g('streamfarm', ['Fazenda de streams', 'Stream farm'], ['Plays falsos comprados; derrubada, multa, escândalo e lista negra.', 'Bought fake plays; takedown, fine, scandal and blacklist.']);
g('payola', ['Jabá (payola)', 'Payola'], ['Pagamento oculto para tocar uma música na rádio/TV. Ilegal nos EUA desde 1960 (escândalo de Alan Freed).', 'Hidden payment to get a song played on radio/TV. Illegal in the US since 1960 (Alan Freed scandal).'], ['Promotor independente "limpa" o pagamento — até alguém investigar (2005).', 'An independent promoter "launders" the payment — until someone investigates (2005).'], ['jabá', 'jaba']);
g('plugger', ['Promotor de rádio (plugger)', 'Radio plugger'], ['Profissional que leva sua faixa aos diretores de programação.', 'Professional pitching your track to program directors.']);
g('rotation', ['Rotação', 'Rotation'], ['Frequência de execução na rádio: leve, média, pesada.', 'How often radio plays it: light, medium, heavy.']);
g('capa', ['CA / PA', 'CA / PA'], ['Habilidade Atual e Potencial (estilo Football Manager), 0–200 em estrelas. PA é escondido e estimado com incerteza.', 'Current and Potential Ability (Football Manager style), 0–200 in stars. PA is hidden and estimated with uncertainty.'], ['Olheiro e convivência estreitam a faixa: "3–5★" vira "4★".', 'Scouting and contact narrow the range: "3–5★" becomes "4★".'], ['ca', 'pa', 'potencial', 'potential']);
g('hype', ['Hype', 'Hype'], ['Expectativa de curto prazo em torno de um artista; cai rápido e multiplica vendas no lançamento.', 'Short-term buzz around an act; fades fast and multiplies launch sales.']);
g('stress', ['Estresse', 'Stress'], ['Medida única (curto e longo prazo) de saúde, cansaço, moral e pressão; estoura em recaída, esgotamento ou escândalo.', 'Single measure (short and long term) of health, fatigue, morale and pressure; bursts into relapse, burnout or scandal.']);
g('runway', ['Fôlego de caixa', 'Cash runway'], ['Meses que o caixa aguenta com o custo fixo atual.', 'Months the cash lasts at current fixed costs.'], ['$60k de caixa e $20k/mês de custo = 3 meses.', '$60k cash and $20k/month costs = 3 months.']);
g('pl', ['DRE (resultado)', 'P&L (income statement)'], ['Receita − custos do período, separando operacional, não operacional, impostos.', 'Revenue − costs for the period, separating operating, non-operating and taxes.'], ['Empréstimo não é receita; venda de imóvel não é operacional.', 'A loan is not revenue; selling property is not operating.'], ['dre']);
g('opex', ['Custo operacional', 'Operating cost'], ['Gastos do dia a dia: salários, gravação, marketing, prensagem.', 'Day-to-day spend: salaries, recording, marketing, pressing.']);
g('capex', ['Investimento (capex)', 'Capex'], ['Compra de ativos duradouros (sede, estúdio, casa de show); vai para investimentos.', 'Purchase of lasting assets (HQ, studio, venue); booked as investing.']);
g('receivables', ['Contas a receber', 'Receivables'], ['Vendas já feitas cujo dinheiro chega depois (lojas pagam em 60–90 dias).', 'Sales made whose cash arrives later (shops pay in 60–90 days).'], ['Loja que quebra leva o que devia.', 'A shop going bust takes what it owed.'], ['recebíveis']);
g('equity', ['Participação (equity)', 'Equity'], ['Fatia da empresa vendida a sócios; dá caixa e dilui controle.', 'Share of the company sold to partners; gives cash and dilutes control.']);
g('ipo', ['Abertura de capital', 'IPO'], ['Vender ações na bolsa: muito caixa, cobrança trimestral.', 'Selling shares on the exchange: lots of cash, quarterly scrutiny.']);
g('catalog', ['Catálogo', 'Catalog (back catalogue)'], ['Discos com mais de ~18 meses; renda estável e ativo avaliado por múltiplo.', 'Records older than ~18 months; steady income and an asset valued by multiple.'], ['Catálogos foram vendidos a 15–30× a receita anual nos anos 2020.', 'Catalogs sold at 15–30× annual revenue in the 2020s.'], ['back catalogue']);
g('returns', ['Devoluções', 'Returns'], ['Lojas devolvem disco não vendido; você reembolsa. "Saiu ouro, voltou platina" (1979).', 'Shops send back unsold records; you refund. "Shipped gold, returned platinum" (1979).']);
g('cutout', ['Ponta de estoque', 'Cut-out'], ['Disco encalhado vendido barato (capa furada) ou destruído.', 'Unsold record sold cheap (punched sleeve) or destroyed.']);
g('retail', ['Varejo', 'Retail'], ['Lojas e redes; ditam espaço na prateleira e prazo de pagamento.', 'Shops and chains; they set shelf space and payment terms.']);
g('rollout', ['Rollout', 'Rollout'], ['Sequência de lançamento: teaser, singles, clipe, álbum, turnê.', 'Release sequence: teaser, singles, video, album, tour.']);
g('saturation', ['Saturação', 'Saturation'], ['Repetir o mesmo canal rende cada vez menos (retorno decrescente).', 'Repeating the same channel yields less each time (diminishing returns).']);
g('guarantee', ['Garantia (cachê fixo)', 'Guarantee'], ['Valor mínimo pago ao artista pelo show, venda ou não.', 'Minimum fee paid to the act for the show, whatever sells.']);
g('doorsplit', ['Divisão da porta', 'Door split'], ['Artista recebe % da bilheteria (às vezes após os custos: "versus deal").', 'The act gets a % of the door (sometimes after costs: "versus deal").'], ['80/20 após custos é comum em casas pequenas.', '80/20 after costs is common in small venues.'], ['versus']);
g('rider', ['Rider', 'Rider'], ['Exigências técnicas e de camarim do artista.', 'The act\'s technical and backstage requirements.']);
g('radius', ['Cláusula de raio', 'Radius clause'], ['Proíbe o artista de tocar perto do festival por semanas antes/depois.', 'Forbids the act from playing near the festival for weeks before/after.']);
g('commission', ['Comissão', 'Commission'], ['Parte do empresário/agente sobre o ganho do cliente (10–20%).', 'Manager/agent cut of the client\'s earnings (10–20%).']);
g('points', ['Pontos (produtor)', 'Points (producer)'], ['Royalty do produtor, em pontos percentuais da receita do disco.', 'Producer royalty, in percentage points of the record\'s revenue.'], ['3 pontos = 3% (recuperáveis).', '3 points = 3% (recoupable).']);
g('session', ['Músico de sessão', 'Session musician'], ['Músico contratado por gravação, sem royalty (ex.: Wrecking Crew, Funk Brothers).', 'Musician hired per session, no royalty (e.g. Wrecking Crew, Funk Brothers).']);
g('licensing', ['Licenciamento', 'Licensing'], ['Ceder a outro selo o direito de lançar seu disco num território, por % ou adiantamento.', 'Granting another label the right to release your record in a territory, for a % or advance.']);
g('merch', ['Merch', 'Merch'], ['Camisetas, pôsteres e itens do artista; margem alta, depende de fãs leais.', 'T-shirts, posters and act items; high margin, depends on loyal fans.']);
g('noncompete', ['Não-concorrência', 'Non-compete'], ['Ao vender o selo, você fica proibido de abrir outro no mesmo ramo por um tempo.', 'After selling the label you may not open another in the same field for a while.']);
g('major', ['Major', 'Major label'], ['Grande gravadora com distribuição própria global (ex.: as "Big Three" atuais).', 'Big label with its own global distribution (e.g. today\'s "Big Three").']);
g('indie', ['Indie', 'Indie label'], ['Selo independente das majors; usa distribuidoras independentes ou P&D.', 'Label independent of the majors; uses indie distributors or P&D.']);
g('chartmeth', ['Metodologia das paradas', 'Chart methodology'], ['Regra do que conta na parada (vendas, rádio, streams, peso de cada um); muda por época.', 'Rule of what counts on the chart (sales, radio, streams, weights); changes by era.'], ['Billboard passou a contar streams em 2014 (álbuns).', 'Billboard began counting streams for albums in 2014.']);
g('rumor', ['Boato', 'Rumor'], ['Fato com visibilidade parcial: pode ser verdade ou não e se espalha por país.', 'Fact with partial visibility: may be true or not and spreads by country.']);
g('streisand', ['Efeito Streisand', 'Streisand effect'], ['Tentar abafar algo o torna mais conhecido; forte em gêneros rebeldes.', 'Trying to suppress something makes it more famous; strong in rebel genres.']);
g('feud', ['Rixa', 'Feud'], ['Conflito entre dois atos que escala: farpas, diss, guerra de faixas, briga.', 'Conflict between two acts that escalates: jabs, diss, track war, fight.']);
g('rico', ['RICO', 'RICO'], ['Lei dos EUA (1970) contra crime organizado, usada em casos da indústria.', 'US law (1970) against organized crime, used in industry cases.']);
g('relic', ['Relíquia', 'Relic'], ['Objeto histórico real (instrumento, fita master) que pode ser comprado, emprestado ou roubado.', 'Real historic object (instrument, master tape) that can be bought, lent or stolen.']);
g('prenup', ['Pacto pré-nupcial', 'Prenup'], ['Contrato que protege bens (e o selo) num divórcio.', 'Contract protecting assets (and the label) in a divorce.']);
g('remix', ['Remix', 'Remix'], ['Nova versão por DJ/produtor; abre pistas e playlists de clube.', 'New version by a DJ/producer; opens clubs and club playlists.']);
g('rerecord', ['Regravação (re-record)', 'Re-record'], ['O artista grava de novo o próprio disco para ter um master próprio.', 'The act records their own album again to own a new master.']);
g('audit', ['Auditoria de royalties', 'Royalty audit'], ['Conferir os extratos de quem paga; costuma achar dinheiro devido.', 'Checking statements from whoever pays; usually finds money owed.']);
g('imprint', ['Selo-vaidade', 'Vanity imprint'], ['Selo dentro do seu com o nome de uma estrela, que indica talentos e leva parte da receita.', 'A label within yours named for a star, who scouts talent and takes a revenue share.']);
g('jv', ['Joint venture', 'Joint venture'], ['Sociedade com uma major num gênero: aporte e distribuição em troca de parte da receita.', 'Partnership with a major in a genre: funding and distribution for a revenue share.']);
g('cue', ['Cue sheet', 'Cue sheet'], ['Lista das músicas usadas num filme/programa com duração; base para pagar execução.', 'List of music used in a film/show with timings; basis for paying performance.']);
g('postmortem', ['Post-mortem', 'Post-mortem'], ['Análise previsto × realizado de um lançamento (alcance, retorno, conversão, campanha).', 'Forecast × actual analysis of a release (reach, retention, conversion, campaign).']);
g('isrc', ['ISRC / ISWC', 'ISRC / ISWC'], ['Códigos únicos da gravação (ISRC) e da obra (ISWC); sem eles, royalties se perdem.', 'Unique codes for the recording (ISRC) and the work (ISWC); without them royalties get lost.']);
g('dsp', ['DSP (plataforma)', 'DSP'], ['Serviço digital de música (loja ou streaming).', 'Digital service provider (store or streaming).']);
g('ar', ['A&R', 'A&R'], ['Artistas e repertório: quem descobre, contrata e desenvolve artistas.', 'Artists and repertoire: who discovers, signs and develops acts.']);
g('controlled', ['Composição controlada', 'Controlled composition'], ['Cláusula que reduz o mecânico pago ao artista-autor (ex.: 75% da taxa).', 'Clause cutting the mechanical paid to the artist-writer (e.g. 75% of the rate).']);
g('escalator', ['Escalonamento de royalty', 'Royalty escalator'], ['Royalty sobe quando as vendas passam de metas (ex.: +1% após 500 mil).', 'Royalty rises when sales pass targets (e.g. +1% after 500k).']);
g('keyman', ['Cláusula de pessoa-chave', 'Key-man clause'], ['O artista pode sair se o executivo que o contratou deixar o selo.', 'The act may leave if the executive who signed them leaves the label.']);
g('gold', ['Disco de ouro / platina', 'Gold / platinum'], ['Certificação por vendas (EUA: ouro 500 mil, platina 1 milhão; varia por país e época).', 'Sales certification (US: gold 500k, platinum 1M; varies by country and era).']);

export const GLOSS18: readonly Gloss18[] = G;
export const gloss18 = (id: string): Gloss18 | undefined => G.find((x) => x.id === id);

const norm = (x: string): string => x.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase();
/** Busca tolerante a acentos em termo, apelidos e definição (termo pesa mais). */
export function searchGloss18(q: string): Gloss18[] {
  const k = norm(q.trim());
  if (!k) return [...G];
  const score = (x: Gloss18): number => {
    const t = norm(`${x.term.pt} ${x.term.en} ${x.id} ${(x.alt ?? []).join(' ')}`);
    if (t.includes(k)) return 2;
    return norm(`${x.def.pt} ${x.def.en}`).includes(k) ? 1 : 0;
  };
  return G.map((x) => [x, score(x)] as const).filter((x) => x[1] > 0).sort((a, b) => b[1] - a[1]).map((x) => x[0]);
}
