// Rodada 18 (artist18) — ajuda das páginas "Contratos do artista" e "Sociedades" e das suas abas.
import { H, T } from './help18';

H('artist18', ['Contratos do artista', 'Artist deals'],
  ['O outro lado da mesa: selos NPC observam sua banda e mandam propostas (gravação, distribuição, desenvolvimento, compra do seu contrato), você negocia, a banda vota, e depois o selo decide verba, single, imagem, datas, opções e dispensa. Inclui seu extrato de artista com prestações de contas, empresário, agente de shows, editora e a comparação faça-você-mesmo × selo.', 'The other side of the table: NPC labels watch your band and send offers (record, distribution, development, contract buyouts), you negotiate, the band votes, and then the label decides budget, single, image, dates, options and drops. Includes your artist ledger with royalty statements, manager, booking agent, publisher and the DIY vs label comparison.'],
  ['Com duas propostas na mesa, contraproponha: vira leilão. Ex.: um advogado ($1,5k) revela que a proposta "generosa" recupera tudo, cruzado, com contas anuais — peça auditoria e contas trimestrais antes de assinar.', 'With two offers on the table, counter: it becomes an auction. E.g. a lawyer ($1.5k) reveals that the "generous" offer recoups everything, cross-collateralized, with yearly statements — ask for audit and quarterly statements before signing.'],
  [['Adiantamento não é presente: sai dos seus royalties.', 'An advance is not a gift: it comes out of your royalties.'], ['Prioridade baixa no selo = disco enterrado ou dispensa.', 'Low priority at the label = buried record or being dropped.']],
  ['cp17-musician', 'shared18', 'finance'], ['advance', 'recoup', 'crosscoll', 'royalty', 'option', 'deal360', 'masters', 'audit', 'commission', 'pd', 'publishing']);
H('shared18', ['Sociedades', 'Partnerships'],
  ['Carreiras compartilhadas: empresas com sócios NPC (selo, festival, estúdio ou imprint com um selo), com participação, votos, estilo do sócio, dividendos, chamadas de capital, compra e venda de participação e briga; a banda como sociedade (divisão do dinheiro) e o conflito de interesse de quem tem selo e banda.', 'Shared careers: companies with NPC partners (label, festival, studio or an imprint with a label), with equity, votes, partner style, dividends, capital calls, buying and selling stakes and fallouts; the band as a partnership (money split) and the conflict of interest of owning a label and a band.'],
  ['Escolha o sócio pelo estilo. Ex.: um sócio "visionário" vota contra dividendos e a favor de expandir; em 50/50, votos diferentes travam tudo e azedam a relação — 70% dá o controle, mas ele hesita mais em topar.', 'Pick the partner by style. E.g. a "visionary" partner votes against dividends and for expansion; at 50/50 split votes deadlock and sour things — 70% gives you control, but they are less likely to agree.'],
  [['Humor do sócio no chão vira briga: compre, venda ou dissolva.', 'A partner\'s mood at rock bottom becomes a fallout: buy, sell or dissolve.']], ['artist18', 'cp17-musician'], ['equity', 'imprint', 'jv']);

T('artist18', 'offers', ['Propostas', 'Offers'], ['Propostas abertas com termos, nota para vocês (com o porquê), aviso do assessor, o que dizem do selo e o voto da banda; quem está de olho em vocês.', 'Open offers with terms, your score (with the why), advisor warning, what people say about the label and the band vote; who is watching you.'], ['Contraproponha um ponto por vez. Ex.: "Master de volta" numa proposta de major costuma virar reversão em 15 anos.', 'Counter one point at a time. E.g. "Master back" on a major\'s offer usually becomes a 15-year reversion.'], ['advance', 'royalty', 'recoup']);
T('artist18', 'deal', ['Seu contrato', 'Your deal'], ['Contrato vigente: prioridade no selo, saldo a recuperar, fundo de gravação, 360, prazo e opções; auditar, renegociar, comprar a saída, processar.', 'Current deal: priority at the label, unrecouped balance, recording fund, 360, term and options; audit, renegotiate, buy your way out, sue.'], ['Renegocie quando crescer. Ex.: fama +12 desde a assinatura destrava pedir royalty maior.', 'Renegotiate when you grow. E.g. fame +12 since signing unlocks asking for a higher royalty.'], ['option', 'audit', 'keyman']);
T('artist18', 'ledger', ['Extrato e contas', 'Ledger and statements'], ['Prestações de contas (ganho, recuperado, a pagar, saldo, atraso) e o extrato do artista.', 'Royalty statements (earned, recouped, payable, balance, lateness) and the artist ledger.'], ['Contas atrasadas ou magras? Audite. Ex.: selo desonesto "arredonda" até 15% e a auditoria recupera com juros.', 'Late or thin statements? Audit. E.g. a dishonest label shaves up to 15% and an audit recovers it with interest.'], ['recoup', 'audit']);
T('artist18', 'team', ['Equipe e editora', 'Team and publisher'], ['Empresário (comissão, leitura de contratos, negociação), agente de shows, editora (administração, coedição, edição integral) e marcas.', 'Manager (commission, contract reading, negotiation), booking agent, publisher (administration, co-publishing, full publishing) and brands.'], ['Coedição dá adiantamento e sync; administração só cobra melhor. Ex.: empresário real com negociação 90 sobe a chance das contrapropostas.', 'Co-publishing gives an advance and sync; administration just collects better. E.g. a real manager with 90 negotiation lifts counter-offer odds.'], ['commission', 'publishing', 'sync']);
T('artist18', 'diy', ['Faça você mesmo × selo', 'DIY vs label'], ['Quanto fica com vocês de cada US$ 100, alcance, adiantamento e anos para recuperar, por caminho.', 'How much of every US$100 you keep, reach, advance and years to recoup, per path.'], ['Selo dá alcance e dinheiro hoje; DIY dá margem e o master. Ex.: 15% de royalty com alcance ×2,5 pode render mais que 60% sozinho.', 'A label gives reach and money now; DIY gives margin and the master. E.g. a 15% royalty with ×2.5 reach can beat 60% on your own.'], ['distribution', 'aggregator', 'masters']);
T('shared18', 'ven', ['Sociedades', 'Partnerships'], ['Suas empresas com sócios: parte, valor, caixa, humor e estilo do sócio, propostas e votações.', 'Your companies with partners: stake, value, cash, partner mood and style, motions and votes.'], ['Dividendo agrada o ganancioso; expandir agrada o visionário. Ex.: com 30% você só influencia.', 'Dividends please the greedy; expansion pleases the visionary. E.g. at 30% you only influence.'], ['equity']);
T('shared18', 'new', ['Nova sociedade', 'New partnership'], ['Escolha tipo, sócio e participação; veja a chance de ele topar e o aporte.', 'Pick type, partner and stake; see the chance they agree and the capital.'], ['Imprint com selo exige fama 35+. Ex.: artista famoso amigo topa mais.', 'An imprint with a label needs fame 35+. E.g. a famous friend agrees more readily.'], ['imprint', 'jv']);
T('shared18', 'band', ['Banda e conflitos', 'Band and conflicts'], ['Como a banda divide o dinheiro (moral e mágoa) e, se você tem selo, a política de royalties da própria banda.', 'How the band splits money (morale and resentment) and, if you own a label, your own band\'s royalty policy.'], ['"Você como líder" rende mais e acumula mágoa. Ex.: "em causa própria" sobe a banda nas paradas e derruba a confiança dos outros artistas.', '"You as leader" pays more and builds resentment. E.g. "self-dealing" lifts your band on the charts and sinks other acts\' trust.']);
T('cp17-musician', 'artist18', ['Contratos do artista', 'Artist deals'], ['Propostas de selos, contrato, extrato e equipe da sua banda.', 'Label offers, deal, ledger and team for your band.'], ['Ex.: compare propostas na aba "Faça você mesmo × selo".', 'E.g. compare offers in the "DIY vs label" tab.'], ['advance', 'recoup']);
T('cp17-musician', 'shared18', ['Sociedades', 'Partnerships'], ['Empresas com sócios NPC, divisão da banda e conflito de interesse.', 'Companies with NPC partners, band split and conflict of interest.'], ['Ex.: funde um estúdio com um artista famoso.', 'E.g. found a studio with a famous artist.'], ['equity']);
