// Rodada 13 — dados do Novo Jogo sem DOM: anos de início (um nome único e fiel por ano), grupos de traços
// e os textos de ajuda "(?)" de cada seção.

import { l, type L } from '../data/world';

/** Cada ano da lista tem um nome próprio (nada de "LP e TV" duas vezes). */
export const ERA_NAMES: Record<number, L> = {
  1920: l('Goma-laca e rádio nascente', 'Shellac and early radio'),
  1925: l('Gravação elétrica e o microfone', 'Electrical recording and the microphone'),
  1927: l('Cinema falado e o jazz na tela', 'Talkies and jazz on screen'),
  1930: l('Depressão: o rádio segura o disco', 'The Depression: radio keeps records alive'),
  1935: l('Era do swing', 'The swing era'),
  1940: l('Big bands e a guerra na Europa', 'Big bands and war in Europe'),
  1945: l('Fim da guerra e o bebop', 'War\'s end and bebop'),
  1948: l('Nasce o LP', 'The LP is born'),
  1950: l('O compacto de 45 e a jukebox', 'The 45 single and the jukebox'),
  1954: l('O rock\'n\'roll explode', 'Rock\'n\'roll explodes'),
  1955: l('Rockabilly e as rádios Top 40', 'Rockabilly and Top 40 radio'),
  1958: l('Bossa nova e o estéreo', 'Bossa nova and stereo'),
  1960: l('Twist e girl groups', 'The twist and girl groups'),
  1962: l('Surf, soul de Detroit e grupos beat', 'Surf, Detroit soul and beat groups'),
  1964: l('Invasão britânica', 'The British Invasion'),
  1965: l('Folk-rock e canção de protesto', 'Folk rock and protest songs'),
  1967: l('Verão do amor e psicodelia', 'Summer of love and psychedelia'),
  1969: l('Woodstock e a contracultura', 'Woodstock and the counterculture'),
  1970: l('Rock progressivo e cantautores', 'Prog rock and singer-songwriters'),
  1973: l('Funk, soul e rock de arena', 'Funk, soul and arena rock'),
  1975: l('A disco sobe e o reggae ganha o mundo', 'Disco rises and reggae goes global'),
  1977: l('Punk e a febre da discoteca', 'Punk and disco fever'),
  1979: l('Hip hop e o walkman', 'Hip hop and the walkman'),
  1980: l('New wave e sintetizadores', 'New wave and synthesizers'),
  1981: l('MTV e os videoclipes', 'MTV and music videos'),
  1983: l('Chega o CD', 'The CD arrives'),
  1985: l('Live Aid e o pop global', 'Live Aid and global pop'),
  1990: l('House, rave e o vinil em queda', 'House, rave and falling vinyl'),
  1991: l('Grunge e rap no topo', 'Grunge and rap on top'),
  1995: l('O CD no auge', 'The CD at its peak'),
  1999: l('Napster e o pânico digital', 'Napster and the digital panic'),
  2000: l('Pop teen e vendas recordes de CD', 'Teen pop and record CD sales'),
  2001: l('iPod: a música no bolso', 'The iPod: music in your pocket'),
  2005: l('YouTube e redes sociais', 'YouTube and social media'),
  2008: l('Nasce o streaming', 'Streaming is born'),
  2010: l('Smartphones e música na nuvem', 'Smartphones and cloud music'),
  2013: l('Lançamentos-surpresa e playlists', 'Surprise drops and playlists'),
  2015: l('O streaming passa o download', 'Streaming overtakes downloads'),
  2020: l('Pandemia e shows on-line', 'Pandemic and livestreams'),
  2025: l('Algoritmos e vídeos curtos', 'Algorithms and short video'),
  2030: l('Arco Neural: a IA entra no estúdio', 'Neural Arc: AI enters the studio'),
  2035: l('Vozes sintéticas', 'Synthetic voices'),
  2039: l('Fim do arco: humanos contra sintéticos', 'The arc\'s end: humans versus synths'),
};
export const START_YEARS13: { year: number; label: L }[] = Object.keys(ERA_NAMES).map(Number).sort((a, b) => a - b)
  .map((year) => ({ year, label: { pt: `${year} — ${ERA_NAMES[year].pt}`, en: `${year} — ${ERA_NAMES[year].en}` } }));

/** Grupos de traços na criação (o que não estiver aqui cai em "Outros"). */
export const TRAIT_GROUPS: { id: string; name: L; desc: L; ids: string[] }[] = [
  { id: 'social', name: l('Trato com as pessoas', 'Dealing with people'), desc: l('Confiança dos artistas, ofertas e tramas.', 'Artist trust, offers and schemes.'), ids: ['charismatic', 'shy', 'honest', 'schemer'] },
  { id: 'money', name: l('Dinheiro e ambição', 'Money and ambition'), desc: l('Adiantamentos, salários, patrimônio e valor da empresa.', 'Advances, salaries, wealth and company value.'), ids: ['generous', 'greedy', 'frugal', 'ambitious'] },
  { id: 'pace', name: l('Ritmo de trabalho', 'Work rhythm'), desc: l('Estresse, tempo livre, aprendizado e saúde.', 'Stress, free time, learning and health.'), ids: ['calm', 'workaholic', 'bohemian', 'disciplined'] },
  { id: 'ear', name: l('Ouvido e criação', 'Ear and craft'), desc: l('Qualidade das músicas, crítica e faro para talento.', 'Song quality, critics and a nose for talent.'), ids: ['visionary', 'perfectionist', 'intellectual', 'perfect_pitch'] },
  { id: 'temper', name: l('Temperamento (puxa gêneros)', 'Temperament (pulls genres)'), desc: l('Bônus com certas famílias de gênero e o som da sua própria banda.', 'Bonuses with certain genre families and your own band\'s sound.'), ids: ['rebel', 'traditional', 'romantic', 'spiritual'] },
];

/** Textos de ajuda "(?)" do Novo Jogo: o que cada opção muda na partida. */
export const HELP: Record<string, L> = {
  company: l('Nome que aparece nas paradas, contratos e notícias. Não muda números. Ao assumir uma gravadora existente, vem o nome dela.', 'The name shown on charts, contracts and news. No effect on numbers. Taking over a label uses its name.'),
  role: l('Gravadora: você só administra o selo. Híbrido: você também tem uma banda própria (área Artistas), que grava e faz shows — mais renda e mais coisas para cuidar.', 'Label: you only run the label. Hybrid: you also have your own band (Artists area) that records and tours — more income and more to look after.'),
  band: l('Nome e gênero da sua banda no papel Híbrido. O gênero define público, paradas e mercados onde ela rende mais.', 'Name and genre of your band in the Hybrid role. Genre sets audience, charts and the markets where it does best.'),
  scenario: l('Ponto de partida do selo: do zero (pouco caixa, nenhum artista), emergente (alguns atos e caixa médio) ou estabelecido (elenco, catálogo e custos maiores).', 'Starting point: from zero (little cash, no acts), emerging (a few acts and mid cash) or established (roster, catalog and higher costs).'),
  custom: l('Ajuste fino do começo: caixa, patrimônio, sede, estúdio, elenco, equipe, mercados e reputação. Vazio = padrão do cenário. Valores altos deixam o jogo mais fácil.', 'Fine-tune the start: cash, wealth, HQ, studio, roster, staff, markets and reputation. Blank = scenario default. High values make the game easier.'),
  takeover: l('Fundar um selo novo começa do zero; assumir uma gravadora existente herda elenco, contratos, catálogo, caixa — e as dívidas e a equipe dela.', 'Founding starts from scratch; taking over inherits roster, contracts, catalog, cash — and its debts and staff.'),
  main: l('Onde seu tempo vai no começo. Cada carreira ocupa parte da agenda; passar de 100% gera estresse todo mês. Dá para começar ou largar carreiras durante o jogo (Você → Carreiras).', 'Where your time goes at the start. Each career takes part of your schedule; above 100% you gain stress every month. You can start or drop careers later (You → Careers).'),
  origin: l('De onde você veio antes do selo. Aplicada uma vez no começo: atributos, habilidades musicais, dinheiro, reputação; e bônus permanentes e contatos no mercado de serviços. Diferente da Trajetória (aba Personagem), que define a base da ficha e o perfil do selo.', 'Where you came from before the label. Applied once at the start: attributes, music skills, money, reputation; plus permanent bonuses and contacts in the services market. Different from the Path (Character tab), which sets your sheet\'s base and label profile.'),
  ambition: l('O que te satisfaz. Todo janeiro o jogo confere a meta do ano: cumprida, −6 de estresse e um bônus no ano seguinte; frustrada, +6 de estresse. Trocar durante o jogo custa estresse.', 'What satisfies you. Every January the game checks the year\'s goal: met, −6 stress and a bonus next year; missed, +6 stress. Changing it later costs stress.'),
  year: l('Ano de início (1920–2039). Define tecnologia, formatos, gêneros que já existem, preços (dólares da época), rivais e artistas reais disponíveis. Começar tarde é mais difícil: pirataria, streaming e mercado saturado.', 'Start year (1920–2039). Sets technology, formats, which genres exist, prices (period dollars), rivals and available real artists. Starting late is harder: piracy, streaming and a saturated market.'),
  city: l('Cidade da sede: mercado de casa, cena local, artistas que aparecem primeiro e custos. Grandes centros têm mais público e mais concorrência.', 'HQ city: home market, local scene, which acts show up first and costs. Big hubs have more audience and more competition.'),
  mode: l('Histórico: o mundo segue a história real (formatos, artistas, eventos). Livre: a história é ponto de partida, mas diverge. Caos: tudo pode acontecer em qualquer ordem.', 'Historic: the world follows real history (formats, acts, events). Free: history is a starting point but diverges. Chaos: anything can happen in any order.'),
  realNames: l('Liga os nomes reais de artistas, selos, festivais, mídia e prêmios. Desligado, o universo é ficcional (mesmas mecânicas).', 'Turns on real names for acts, labels, festivals, media and awards. Off, the universe is fictional (same mechanics).'),
  realFates: l('Só no modo histórico: artistas reais tendem a morrer no ano em que morreram na vida real.', 'Historic mode only: real artists tend to die in the year they did in real life.'),
  seed: l('Semente do mundo: a mesma semente com as mesmas escolhas gera o mesmo mundo. Use 🎲 para sortear outra.', 'World seed: the same seed with the same choices builds the same world. Use 🎲 to roll another.'),
  world: l('Gera anos de história antes do início (bandas, hits, lendas, selos) ou continua um mundo salvo de uma partida anterior.', 'Generates years of history before the start (bands, hits, legends, labels) or continues a world saved from a previous run.'),
  rivals: l('Quantas e quais gravadoras concorrem com você. Mais rivais = disputa por artistas, paradas e rádio. "Todos iguais" faz todas começarem do zero, como você.', 'How many and which labels compete with you. More rivals = fights over acts, charts and radio. "All equal" makes them all start from zero like you.'),
  storyteller: l('O narrador É o diretor criativo da partida (uma escolha só): decide o ritmo dos eventos do mês (quantos, ondas de crise e bonança, se alivia quando o caixa aperta), a voz das notícias, quanto drama ele joga em você e em TODOS os personagens (situações — NPCs respondem pelos próprios traços; você escolhe e vê as consequências) e o tom (mais escândalo ou mais superação). Dá para ver o diretor em Mundo → Mundo vivo.', 'The storyteller IS the run\'s creative director (a single choice): it sets the pace of monthly events (how many, waves of crisis and boom, whether it eases off when cash runs low), the news voice, how much drama it throws at you and at EVERY character (situations — NPCs answer by their own traits; you choose and see the consequences) and the tone (more scandal or more triumph). See the director in World → Living world.'),
  freedom17: l('Quanto o diretor deixa os NPCs mudarem o mundo: artistas rompem com empresários e selos, ficam independentes ou assinam em outro lugar, abrem gravadoras, viram empresários; selos adiam lançamentos para fugir de estrelas, vendem merch, fazem guerra de preços, aliciam, se fundem. Contida = mundo estável; Solta = cada partida muito diferente. No modo "Vida real exata", artistas reais seguem a história.', 'How much the director lets NPCs change the world: acts break with managers and labels, go independent or sign elsewhere, open labels, become managers; labels delay releases to dodge stars, sell merch, wage price wars, poach, merge. Restrained = a stable world; Unleashed = every run very different. In "Exact real life" mode, real artists follow history.'),
  difficulty: l('Fácil: caixa inicial ×1,5 e previsões de olheiros mais precisas. Difícil: caixa ×0,7, previsões mais incertas e gravadoras à venda com termos piores.', 'Easy: starting cash ×1.5 and sharper scouting forecasts. Hard: cash ×0.7, fuzzier forecasts and worse terms on labels for sale.'),
  ironman: l('Um único save, gravado automaticamente: sem voltar atrás nas decisões.', 'A single, auto-written save: no taking decisions back.'),
  filters: l('Temas que você não quer ver. Eventos com esses temas são resolvidos em silêncio pela opção mais neutra.', 'Themes you do not want to see. Events with them resolve silently with the most neutral option.'),
  card: l('Uma carta de selo: um bônus passivo e uma meta de longo prazo que dá prestígio quando cumprida.', 'A label card: a passive bonus and a long-term goal that grants prestige when met.'),
  mutators: l('Regras especiais que mudam o mundo inteiro (mais difícil, mais estranho ou mais rápido). Combinam entre si.', 'Special rules that change the whole world (harder, stranger or faster). They stack.'),
  character: l('Você é uma pessoa no mundo: idade, saúde, família e banda. Atributos (ouvido, negociação, carisma, gestão) pesam em contratos, olheiros, ofertas e equipe.', 'You are a person in the world: age, health, family and band. Attributes (ear, negotiation, charisma, management) weigh on deals, scouting, offers and staff.'),
  identity: l('Nome, sexo, pronome e apelido aparecem nas notícias e diálogos. A idade define quanto tempo de carreira você tem antes de pensar em herdeiros.', 'Name, sex, pronoun and nickname appear in news and dialogue. Age sets how long a career you have before thinking of heirs.'),
  instrument: l('Seu instrumento na banda e nas jam sessions. Muda o visual e quais habilidades musicais crescem.', 'Your instrument in the band and jam sessions. Changes your look and which music skills grow.'),
  favGenre: l('Seu gênero do coração: atos da mesma família de gênero ganham +5% de apelo, ofertas melhores e +0,5 de qualidade.', 'Your favourite genre: acts in the same genre family get +5% appeal, better offers and +0.5 quality.'),
  hometown: l('Cidade natal: conhecidos de infância e cena onde você é "de casa". Vazio = a cidade da sede.', 'Hometown: childhood contacts and the scene where you are a local. Blank = the HQ city.'),
  visual: l('Seu estilo: dá pequenos bônus (carisma, imprensa, credibilidade) e muda como artistas te enxergam.', 'Your style: small bonuses (charisma, press, credibility) and how acts see you.'),
  beliefs: l('Visões parecidas aproximam artistas, equipe e parceiros; opostas criam atrito. Vazio = sorteado pela cidade e época.', 'Similar views bring acts, staff and partners closer; opposed ones create friction. Blank = drawn from city and era.'),
  attrs: l('Distribua os pontos livres entre ouvido, negociação, carisma e gestão. Trajetória, traços e habilidades já somam aqui.', 'Spend free points on ear, negotiation, charisma and management. Path, traits and abilities already add here.'),
  path: l('Como você chegou à indústria: base de atributos, instrumento, patrimônio, dívidas iniciais, contatos e o perfil para onde seu selo tende no começo.', 'How you got into the industry: base attributes, instrument, wealth, starting debts, contacts and the profile your label leans toward at first.'),
  traits: l('Até 3 traços de personalidade. Mudam atributos, bônus e reações de artistas e imprensa. Traços opostos não combinam; ✦ = dom que filhos podem herdar.', 'Up to 3 personality traits. They change attributes, bonuses and how acts and press react. Opposites cannot mix; ✦ = a gift children may inherit.'),
  skills: l('Pontos iniciais na árvore de habilidades. O estilo de vida nasce de onde você investe. Você ganha mais pontos todo ano.', 'Starting points in the ability tree. Your lifestyle comes from where you invest. You earn more points every year.'),
  look: l('Aparência do seu personagem. Não é só visual: tom de pele, sexo e idade pesam conforme o país e a época (barreiras históricas como rádio segregada e machismo; a virada por diversidade dos anos 2010). Veja os efeitos e o porquê em Você → Aparência. O retrato envelhece com você.', 'Your character\'s appearance. Not just cosmetic: skin tone, sex and age weigh by country and era (historical barriers like segregated radio and sexism; the 2010s diversity push). See the effects and why in You → Appearance. The portrait ages with you.'),
};
